### ISSUE TITLE
Afsender tydeligt markeret i "Formål"

### ISSUE THREAD

**Issue by MikkelMA** [asayio/asay#30]
Når jeg læser "Formål" på et lovforslag er der tydeligvis en afsender. Dette vil jeg gerne have specificeret. E.g. er det K-Lo der skriver om formålet for et skatteforslag?
<img width="1114" alt="screen shot 2017-10-28 at 16 26 50" src="https://user-images.githubusercontent.com/23225380/32132361-803a9ff8-bbfd-11e7-9a42-a7b0506d7e82.png">

**Comment by holgerthorup** [comment]
@MikkelMA er det vigtige her om det er K-Lo eller at det er Skatteministeren. Eller begge?

**Comment by MikkelMA** [comment]
Først og fremmest: Skatteministeren.

Allerhelst: Karsten Lauritzen, Skatteminister, Venstre
