### ISSUE TITLE
Bug (?) i sortering ved brug af filter

### ISSUE THREAD

**Issue by MikkelMA** [asayio/asay#35]
Fra Christian Møller Andersen, 51 år gammel, Husejer i 3400 Hillerød

Direkte citat fra kilden selv:
"Ved brug af filter på oversigten bør lovforslagene vises i datoorden. F.eks. filter Alle forslag > Status=“Til endelig afstemning”. Her bør det forslag som har deadline først vises først. I min liste er nr. 1 et forslag med deadline om 27 dage, mens det nederste på listen har deadline om 8 dage"

**Comment by holgerthorup** [comment]
Jeg kan ikke umiddelbart genskabe fejlen - udover at den sortere forkert på historikken.

**Comment by MikkelMA** [comment]
Jeg kan heller ikke genskabe denne her. Har prøvet på Mac i Chrom og Safari samt på IOS

**Comment by holgerthorup** [comment]
Det lykkes mig at finde fejlen. Den er hermed udbedret.
