### ISSUE TITLE
Tidligere stemmeafgivning

### ISSUE THREAD

**Issue by akselbll** [asayio/asay#5]
Jeg kan ikke umiddelbart se, hvad jeg tidligere har stemt. Er det bevidst? I så fald forstår jeg ikke umiddelbart hvorfor.

**Comment by holgerthorup** [comment]
Ja, det er bevidst. Det er for at øge det stemmeretlige privatliv, samt reducere risikoen for valgfusk, hvor en udefrakommende kan betale eller tvinge en anden bruger til at stemme noget specifikt. Ved kun at tillade brugeren at se udfaldet af sin stemme i stemmeøjeblikket, er det ikke muligt at dokumentere den faktiske stemme overfor anden part.
